# This service is built from the Dockerfile in the current directory.
services:
  server:
    container_name: adeeb_hono
    build:
      context: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis

  db:
    # Container name is used as ${host} when connecting to database
    container_name: adeeb_mongo
    image: mongo:7-jammy
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: adeeb
      MONGO_INITDB_ROOT_PASSWORD: mongodb
      MONGO_INITDB_DATABASE: adeeb_db
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - db-data:/data/db
    ports:
      - 27017

  redis:
    container_name: adeeb_cache
    restart: unless-stopped
    image: valkey/valkey:7.2.5-bookworm
    command: valkey-server --loglevel warning
    ports:
      - 6379

volumes:
  db-data: